#!/bin/zsh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI

bspc config border_width         1
bspc config window_gap          22
#bspc config top_padding 	131


bspc config split_ratio          0.60
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer	true      
bspc config focused_border_color	"#205659"
# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a QjackCtl layer=above state=floating follow=on manage=off
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
bspc rule -a Plank layer=above manage=on border=off
# bspc rule -a gnome-control-center state=floating
# bspc rule -a looking-glass-client layer=above manage=on border=off
bspc rule -a Gnome-calendar layer=above state=floating folow=on manage=on border=off rectangle=1250x900+2190+37 
bspc rule -a conky sticky=on manage=off lower=on
bspc rule -a Rofi sticky=on  manage=off
bspc rule -a tdrop sticky=false lock=on border=off layer=above state=floating follow=true focus=on rectangle=1350x25+250+15 
bspc rule -a Terminator sticky=false lock=on border=off layer=above state=floating follow=true focus=on rectangle=1350x25+250+15 
bspc rule -a Pycalendar.py state=floating rectangle=600x400+2835+38
bspc rule -a FromScratch state=floating rectangle=600x400+2835+38
bspc rule -a Polybar layer=below 

~/.config/polybar/launch.sh --material &
XDG_SESSION_DESKTOP=x11 XDG_CURRENT_DESKTOP=x11 DESKTOP_SESSION=x11 XDG_SESSION_TYPE=x11 plank
